[2024-02-07T08:48:36.041+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:48:36.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:48:36.043+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:48:36.043+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:48:36.046+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:48:36.046+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:48:36.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:48:36.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.027 seconds
[2024-02-07T08:49:07.049+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:49:07.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:49:07.053+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:49:07.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:49:07.057+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:49:07.056+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:49:07.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:49:07.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.036 seconds
[2024-02-07T08:49:37.312+0000] {processor.py:161} INFO - Started process (PID=730) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:49:37.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:49:37.319+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:49:37.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:49:37.322+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:49:37.321+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:49:37.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:49:37.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.046 seconds
[2024-02-07T08:50:07.556+0000] {processor.py:161} INFO - Started process (PID=797) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:50:07.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:50:07.560+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:50:07.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:50:07.564+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:50:07.563+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:50:07.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:50:07.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.032 seconds
[2024-02-07T08:50:38.436+0000] {processor.py:161} INFO - Started process (PID=863) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:50:38.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:50:38.439+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:50:38.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:50:38.442+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:50:38.441+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:50:38.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:50:38.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T08:51:09.125+0000] {processor.py:161} INFO - Started process (PID=929) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:51:09.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:51:09.128+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:51:09.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:51:09.130+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:51:09.130+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:51:09.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:51:09.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T08:51:40.136+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:51:40.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:51:40.138+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:51:40.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:51:40.141+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:51:40.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:51:40.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:51:40.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T08:52:10.347+0000] {processor.py:161} INFO - Started process (PID=1061) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:52:10.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:52:10.351+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:52:10.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:52:10.354+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:52:10.354+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:52:10.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:52:10.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.034 seconds
[2024-02-07T08:52:40.449+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:52:40.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:52:40.453+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:52:40.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:52:40.455+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:52:40.455+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:52:40.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:52:40.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.031 seconds
[2024-02-07T08:53:11.376+0000] {processor.py:161} INFO - Started process (PID=1193) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:53:11.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:53:11.380+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:53:11.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:53:11.383+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:53:11.383+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:53:11.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:53:11.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.031 seconds
[2024-02-07T08:53:41.660+0000] {processor.py:161} INFO - Started process (PID=1259) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:53:41.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:53:41.664+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:53:41.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:53:41.667+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:53:41.666+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:53:41.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:53:41.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T08:54:12.725+0000] {processor.py:161} INFO - Started process (PID=1325) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:54:12.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:54:12.728+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:54:12.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:54:12.731+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:54:12.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:54:12.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:54:12.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.030 seconds
[2024-02-07T08:54:43.738+0000] {processor.py:161} INFO - Started process (PID=1391) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:54:43.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:54:43.741+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:54:43.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:54:43.745+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:54:43.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:54:43.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:54:43.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T08:55:14.003+0000] {processor.py:161} INFO - Started process (PID=1457) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:55:14.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:55:14.006+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:55:14.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:55:14.009+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:55:14.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:55:14.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:55:14.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.032 seconds
[2024-02-07T08:55:44.077+0000] {processor.py:161} INFO - Started process (PID=1523) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:55:44.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:55:44.079+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:55:44.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:55:44.083+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:55:44.082+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:55:44.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:55:44.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.031 seconds
[2024-02-07T08:56:14.421+0000] {processor.py:161} INFO - Started process (PID=1589) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:56:14.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:56:14.424+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:56:14.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:56:14.426+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:56:14.426+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:56:14.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:56:14.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T08:56:44.723+0000] {processor.py:161} INFO - Started process (PID=1656) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:56:44.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:56:44.727+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:56:44.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:56:44.731+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:56:44.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:56:44.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:56:44.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.037 seconds
[2024-02-07T08:57:14.996+0000] {processor.py:161} INFO - Started process (PID=1722) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:57:14.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:57:14.999+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:57:14.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:57:15.001+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:57:15.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:57:15.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:57:15.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.032 seconds
[2024-02-07T08:57:45.133+0000] {processor.py:161} INFO - Started process (PID=1788) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:57:45.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:57:45.138+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:57:45.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:57:45.142+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:57:45.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:57:45.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:57:45.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.033 seconds
[2024-02-07T08:58:16.195+0000] {processor.py:161} INFO - Started process (PID=1854) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:58:16.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:58:16.198+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:58:16.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:58:16.201+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:58:16.200+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:58:16.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:58:16.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.027 seconds
[2024-02-07T08:58:47.042+0000] {processor.py:161} INFO - Started process (PID=1920) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:58:47.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:58:47.044+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:58:47.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:58:47.047+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:58:47.047+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:58:47.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:58:47.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.027 seconds
[2024-02-07T08:59:17.988+0000] {processor.py:161} INFO - Started process (PID=1986) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:59:17.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:59:17.991+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:59:17.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:59:17.994+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:59:17.994+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:59:17.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:59:18.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.028 seconds
[2024-02-07T08:59:48.899+0000] {processor.py:161} INFO - Started process (PID=2052) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:59:48.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T08:59:48.902+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:59:48.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:59:48.905+0000] {logging_mixin.py:188} INFO - [2024-02-07T08:59:48.904+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T08:59:48.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T08:59:48.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.028 seconds
[2024-02-07T09:00:18.947+0000] {processor.py:161} INFO - Started process (PID=2117) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:00:18.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:00:18.951+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:00:18.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:00:18.954+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:00:18.953+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:00:18.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:00:18.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.030 seconds
[2024-02-07T09:00:49.144+0000] {processor.py:161} INFO - Started process (PID=2183) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:00:49.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:00:49.147+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:00:49.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:00:49.150+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:00:49.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:00:49.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:00:49.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.028 seconds
[2024-02-07T09:01:19.234+0000] {processor.py:161} INFO - Started process (PID=2249) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:01:19.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:01:19.237+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:01:19.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:01:19.239+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:01:19.239+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:01:19.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:01:19.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.029 seconds
[2024-02-07T09:01:50.180+0000] {processor.py:161} INFO - Started process (PID=2316) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:01:50.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:01:50.183+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:01:50.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:01:50.186+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:01:50.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:01:50.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:01:50.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.033 seconds
[2024-02-07T09:02:20.388+0000] {processor.py:161} INFO - Started process (PID=2382) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:02:20.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:02:20.391+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:02:20.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:02:20.393+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:02:20.393+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:02:20.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:02:20.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.027 seconds
[2024-02-07T09:02:51.153+0000] {processor.py:161} INFO - Started process (PID=2448) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:02:51.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:02:51.155+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:02:51.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:02:51.158+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:02:51.158+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:02:51.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:02:51.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.028 seconds
[2024-02-07T09:03:22.167+0000] {processor.py:161} INFO - Started process (PID=2514) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:03:22.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:03:22.171+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:03:22.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:03:22.174+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:03:22.173+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:03:22.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:03:22.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.028 seconds
[2024-02-07T09:03:53.084+0000] {processor.py:161} INFO - Started process (PID=2586) to work on /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:03:53.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/8_emp_snow_cp_v1.py for tasks to queue
[2024-02-07T09:03:53.087+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:03:53.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:03:53.090+0000] {logging_mixin.py:188} INFO - [2024-02-07T09:03:53.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/8_emp_snow_cp_v1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/8_emp_snow_cp_v1.py", line 20, in <module>
    import Generic_commands
ModuleNotFoundError: No module named 'Generic_commands'
[2024-02-07T09:03:53.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/8_emp_snow_cp_v1.py
[2024-02-07T09:03:53.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/8_emp_snow_cp_v1.py took 0.030 seconds
